# Generated by Django 4.2.30 on 2026-05-06 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('team', 'Team')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('past_due', 'Past due'), ('trialing', 'Trialing')], default='active', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('ls_customer_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('ls_subscription_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='orgs.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
